CXX = g++
CXXFLAGS = -std=c++23 -Wall -Wextra -I..
LDFLAGS = -lgtest -lgtest_main -pthread

CXXFLAGS += -I/opt/homebrew/include
LDFLAGS += -L/opt/homebrew/lib

TARGET = AnnotationSetTest
SRC = AnnotationSet.cpp

.PHONY: all test clean

all: $(TARGET)
	./$(TARGET)

$(TARGET): $(SRC) AnnotationSet.hpp
	$(CXX) $(CXXFLAGS) -o $@ $< $(LDFLAGS)

test: $(TARGET)
	./$(TARGET)

clean:
	rm -f $(TARGET)