/**
 * @file ExpressionParserTest.cpp
 * @brief Test suite for ExpressionParser.
 * @author Lewi Anamo
 * @date 2026-2-15
*/

#include "../../../third-party/Catch/single_include/catch2/catch.hpp"
#include "../../source/tools/ExpressionParser.hpp"

/** 
 *  Expressions that are tested here were generated by AI to make sure that we
 *  have a wide variety of test cases.
 *  However, unless specified on a test case/section, the tests were manually written 
 *  by the author.
 */

// Tokenizer Tests
TEST_CASE("Tokenize: Valid expressions", "[tokenize]") {
    
    SECTION("Simple expression") {
        cse498::ExpressionParser parser("3 + 4 * x");

        std::vector<cse498::Token> tokens = parser.getTokens();

        REQUIRE(tokens.size() == 5);

        REQUIRE(tokens[0].type == cse498::TokenType::Literal);
        REQUIRE(tokens[0].value == "3");

        REQUIRE(tokens[1].type == cse498::TokenType::Operator);
        REQUIRE(tokens[1].value == "+");

        REQUIRE(tokens[2].type == cse498::TokenType::Literal);
        REQUIRE(tokens[2].value == "4");

        REQUIRE(tokens[3].type == cse498::TokenType::Operator);
        REQUIRE(tokens[3].value == "*");

        REQUIRE(tokens[4].type == cse498::TokenType::Variable);
        REQUIRE(tokens[4].value == "x");
    }

    SECTION("Expression with variable, parentheses, and index") {
        cse498::ExpressionParser parser;
        REQUIRE_NOTHROW(parser.setRawExpression("2 + (var1 + {0})"));

        std::vector<cse498::Token> tokens = parser.getTokens();

        REQUIRE(tokens.size() == 7);
        REQUIRE(tokens[0].type == cse498::TokenType::Literal);
        REQUIRE(tokens[0].value == "2");

        REQUIRE(tokens[1].type == cse498::TokenType::Operator);
        REQUIRE(tokens[1].value == "+");

        REQUIRE(tokens[2].type == cse498::TokenType::Parenthesis);
        REQUIRE(tokens[2].value == "(");

        REQUIRE(tokens[3].type == cse498::TokenType::Variable);
        REQUIRE(tokens[3].value == "var1");

        REQUIRE(tokens[4].type == cse498::TokenType::Operator);
        REQUIRE(tokens[4].value == "+");

        REQUIRE(tokens[5].type == cse498::TokenType::Index);
        REQUIRE(tokens[5].value == "0");

        REQUIRE(tokens[6].type == cse498::TokenType::Parenthesis);
        REQUIRE(tokens[6].value == ")");
    }

    SECTION("Tokenize: Decimal/Floating point literals") {
        cse498::ExpressionParser parser;
        REQUIRE_NOTHROW(parser.setRawExpression("10.5 * 2"));

        std::vector<cse498::Token> tokens = parser.getTokens();

        REQUIRE(tokens.size() == 3);

        REQUIRE(tokens[0].type == cse498::TokenType::Literal);
        REQUIRE(tokens[0].value == "10.5");

        REQUIRE(tokens[1].type == cse498::TokenType::Operator);
        REQUIRE(tokens[1].value == "*");

        REQUIRE(tokens[2].type == cse498::TokenType::Literal);
        REQUIRE(tokens[2].value == "2");
    }

    SECTION("Multi-char relational operators part 1") {
        cse498::ExpressionParser parser;
        REQUIRE_NOTHROW(parser.setRawExpression("x >= 5 && y < 10"));

        std::vector<cse498::Token> tokens = parser.getTokens();

        REQUIRE(tokens.size() == 7);

        REQUIRE(tokens[0].type == cse498::TokenType::Variable);
        REQUIRE(tokens[0].value == "x");

        REQUIRE(tokens[1].type == cse498::TokenType::Operator);
        REQUIRE(tokens[1].value == ">=");

        REQUIRE(tokens[2].type == cse498::TokenType::Literal);
        REQUIRE(tokens[2].value == "5");

        REQUIRE(tokens[3].type == cse498::TokenType::Operator);
        REQUIRE(tokens[3].value == "&&");

        REQUIRE(tokens[4].type == cse498::TokenType::Variable);
        REQUIRE(tokens[4].value == "y");

        REQUIRE(tokens[5].type == cse498::TokenType::Operator);
        REQUIRE(tokens[5].value == "<");

        REQUIRE(tokens[6].type == cse498::TokenType::Literal);
        REQUIRE(tokens[6].value == "10");
    }

    SECTION("Multi-char relational operators part 2") {
        cse498::ExpressionParser parser;
        REQUIRE_NOTHROW(parser.setRawExpression("a||bx!=y > z"));

        std::vector<cse498::Token> tokens = parser.getTokens();

        REQUIRE(tokens.size() == 7);
        
        REQUIRE(tokens[0].type == cse498::TokenType::Variable);
        REQUIRE(tokens[0].value == "a");

        REQUIRE(tokens[1].type == cse498::TokenType::Operator);
        REQUIRE(tokens[1].value == "||");

        REQUIRE(tokens[2].type == cse498::TokenType::Variable);
        REQUIRE(tokens[2].value == "bx");

        REQUIRE(tokens[3].type == cse498::TokenType::Operator);
        REQUIRE(tokens[3].value == "!=");

        REQUIRE(tokens[4].type == cse498::TokenType::Variable);
        REQUIRE(tokens[4].value == "y");

        REQUIRE(tokens[5].type == cse498::TokenType::Operator);
        REQUIRE(tokens[5].value == ">");

        REQUIRE(tokens[6].type == cse498::TokenType::Variable);
        REQUIRE(tokens[6].value == "z");
    }

    SECTION("Math operators and parentheses") {
        cse498::ExpressionParser parser;
        REQUIRE_NOTHROW(parser.setRawExpression("(a + b) * c - d / e ^ f % g"));

        std::vector<cse498::Token> tokens = parser.getTokens();

        REQUIRE(tokens.size() == 15);

        REQUIRE(tokens[0].type == cse498::TokenType::Parenthesis);
        REQUIRE(tokens[0].value == "(");

        REQUIRE(tokens[1].type == cse498::TokenType::Variable);
        REQUIRE(tokens[1].value == "a");

        REQUIRE(tokens[2].type == cse498::TokenType::Operator);
        REQUIRE(tokens[2].value == "+");

        REQUIRE(tokens[3].type == cse498::TokenType::Variable);
        REQUIRE(tokens[3].value == "b");

        REQUIRE(tokens[4].type == cse498::TokenType::Parenthesis);
        REQUIRE(tokens[4].value == ")");

        REQUIRE(tokens[5].type == cse498::TokenType::Operator);
        REQUIRE(tokens[5].value == "*");

        REQUIRE(tokens[6].type == cse498::TokenType::Variable);
        REQUIRE(tokens[6].value == "c");

        REQUIRE(tokens[7].type == cse498::TokenType::Operator);
        REQUIRE(tokens[7].value == "-");

        REQUIRE(tokens[8].type == cse498::TokenType::Variable);
        REQUIRE(tokens[8].value == "d");

        REQUIRE(tokens[9].type == cse498::TokenType::Operator);
        REQUIRE(tokens[9].value == "/");

        REQUIRE(tokens[10].type == cse498::TokenType::Variable);
        REQUIRE(tokens[10].value == "e");

        REQUIRE(tokens[11].type == cse498::TokenType::Operator);
        REQUIRE(tokens[11].value == "^");

        REQUIRE(tokens[12].type == cse498::TokenType::Variable);
        REQUIRE(tokens[12].value == "f");

        REQUIRE(tokens[13].type == cse498::TokenType::Operator);
        REQUIRE(tokens[13].value == "%");

        REQUIRE(tokens[14].type == cse498::TokenType::Variable);
        REQUIRE(tokens[14].value == "g");
    }
}

// Generated by Gemini 3 Pro 2026-2-16, but under the supervision of author
TEST_CASE("Tokenize: Invalid expressions", "[tokenize]") {
    SECTION("Invalid character") {
        REQUIRE_THROWS_AS(cse498::ExpressionParser("3 + 4 * x @"), cse498::ExpressionException);
    }

    SECTION("Unclosed index") {
        REQUIRE_THROWS_AS(cse498::ExpressionParser("{0 + 1"), cse498::ExpressionException);
    }

    SECTION("Empty index") {
        REQUIRE_THROWS_AS(cse498::ExpressionParser("{} + 1"), cse498::ExpressionException);
    }

    SECTION("Single-character operator") {
        REQUIRE_THROWS_AS(cse498::ExpressionParser("x = 5"), cse498::ExpressionException);
    }

    SECTION("Invalid operator") {
        REQUIRE_THROWS_AS(cse498::ExpressionParser("x $ 5"), cse498::ExpressionException);
    }

    SECTION("Invalid index format") {
        REQUIRE_THROWS_AS(cse498::ExpressionParser("{abc} + 1"), cse498::ExpressionException);
    }

    SECTION("Inalid operator '!'") {
        REQUIRE_THROWS_AS(cse498::ExpressionParser("!x + 1"), cse498::ExpressionException);
    }

    SECTION("Inalid operator '&'") {
        REQUIRE_THROWS_AS(cse498::ExpressionParser("x & 1"), cse498::ExpressionException);
    }

    SECTION("Inalid operator '|'") {
        REQUIRE_THROWS_AS(cse498::ExpressionParser("x | 1"), cse498::ExpressionException);
    }
}


// Validatior Tests
TEST_CASE("ValidateExpr: Valid expressions", "[validate]") {
    cse498::ExpressionParser parser;

    SECTION("Simple valid expression") {
        parser.setRawExpression("3 + 4 * x");
        REQUIRE(parser.isValid() == true);
    }

    SECTION("Valid expression to return true") {
        parser.setRawExpression("(3 + 4) * x - 5 / y ^ 2");
        REQUIRE(parser.isValid() == true);

        parser.setRawExpression("((x))");
        REQUIRE(parser.isValid() == true);

        parser.setRawExpression("a && b || c");
        REQUIRE(parser.isValid() == true);

        parser.setRawExpression("x >= 5 && y < 10");
        REQUIRE(parser.isValid() == true);

        parser.setRawExpression("var + {0} - 3.14 * (var2 / {1})");
        REQUIRE(parser.isValid() == true);

        parser.setRawExpression("x == y || z != 0");
        REQUIRE(parser.isValid() == true);

        parser.setRawExpression("a <= b && c >= d || e < f && g > h");
        REQUIRE(parser.isValid() == true);
    }
}

TEST_CASE("ValidateExpr: Invalid expressions", "[validate]") {
    cse498::ExpressionParser parser;

    SECTION("Invalid Operator order"){
        parser.setRawExpression("3 + * 4");
        REQUIRE(parser.isValid() == false);

        parser.setRawExpression("x / / y");
        REQUIRE(parser.isValid() == false);

        parser.setRawExpression("a && || b");
        REQUIRE(parser.isValid() == false);

        parser.setRawExpression("* x + 1");
        REQUIRE(parser.isValid() == false);

        parser.setRawExpression("x + 1 -");
        REQUIRE(parser.isValid() == false);
    }

    SECTION("Missing Operator") {
        parser.setRawExpression("3 4 + x");
        REQUIRE(parser.isValid() == false);

        parser.setRawExpression("x y z");
        REQUIRE(parser.isValid() == false);

        parser.setRawExpression("(a b) + c");
        REQUIRE(parser.isValid() == false);
    }

    SECTION("Mismatched parentheses") {
        parser.setRawExpression("((x + 2)");
        REQUIRE(parser.isValid() == false);

        parser.setRawExpression("x + 2))");
        REQUIRE(parser.isValid() == false);

        parser.setRawExpression("((x + 2)) + (y * 3");
        REQUIRE(parser.isValid() == false);

        parser.setRawExpression("() + 5");
        REQUIRE(parser.isValid() == false);

        parser.setRawExpression(")(");
        REQUIRE(parser.isValid() == false);
    }
}


// Parse Tests
TEST_CASE("Parse: Valid expressions", "[parse]") {
    cse498::ExpressionParser parser;
    
    SECTION("Simple expression") {
        parser.setRawExpression("3 + 4 * x");

        auto func = parser.parse();

        std::vector<double> arr = {};
        std::map<std::string, double> vars = {{"x", 2}};

        REQUIRE(func(arr, vars) == 11);
    }

    SECTION("Precedence and associativity") {
        parser.setRawExpression("10 - 4 - 2");
        auto func = parser.parse();

        std::vector<double> arr = {};
        std::map<std::string, double> vars = {};

        REQUIRE(func(arr, vars) == Approx(4.0));

        parser.setRawExpression("12 / 3 / 2");
        func = parser.parse();

        REQUIRE(func(arr, vars) == Approx(2.0));

        parser.setRawExpression("2 ^ 3 ^ 2");
        func = parser.parse();

        REQUIRE(func(arr, vars) == Approx(512.0));

        parser.setRawExpression("100 / 10 * 2");
        func = parser.parse();

        REQUIRE(func(arr, vars) == Approx(20.0));

        parser.setRawExpression("(3 + 4) * 2");
        func = parser.parse();

        REQUIRE(func(arr, vars) == Approx(14.0));

        parser.setRawExpression("2 + 3 % 2");
        func = parser.parse();

        REQUIRE(func(arr, vars) == Approx(3.0));

        parser.setRawExpression("2 + 3 * 4 ^ 2");
        func = parser.parse();

        REQUIRE(func(arr, vars) == Approx(50.0));
    }

    // Generated by Gemini 3 Pro 2026-2-16, but under the supervision of author
    SECTION("Logical and relational operators") {
        parser.setRawExpression("x > 5 && y < 10");
        auto func = parser.parse();

        std::vector<double> arr = {};
        std::map<std::string, double> vars = {{"x", 6}, {"y", 9}};

        REQUIRE(func(arr, vars) == Approx(1.0));

        vars["x"] = 4;
        REQUIRE(func(arr, vars) == Approx(0.0));

        vars["x"] = 6;
        vars["y"] = 10;
        REQUIRE(func(arr, vars) == Approx(0.0));

        parser.setRawExpression("a || b != c");
        func = parser.parse();

        vars = {{"a", 0}, {"b", 1}, {"c", 0}};

        REQUIRE(func(arr, vars) == Approx(1.0));

        vars["b"] = 0;

        REQUIRE(func(arr, vars) == Approx(0.0));

        parser.setRawExpression("x <= 5 || y >= 10 && z == 0");
        func = parser.parse();

        vars = {{"x", 4}, {"y", 11}, {"z", 0}};
        REQUIRE(func(arr, vars) == Approx(1.0));

        vars = {{"x", 6}, {"y", 9}, {"z", 0}};
        REQUIRE(func(arr, vars) == Approx(0.0));

        vars = {{"x", 6}, {"y", 11}, {"z", 1}};
        REQUIRE(func(arr, vars) == Approx(0.0));
    }

    SECTION("Expression with variables, indices, and literals") {
        parser.setRawExpression("hp + 10");
        auto func = parser.parse();

        std::vector<double> arr = {};
        std::map<std::string, double> vars = {{"hp", 50}};

        REQUIRE(func(arr, vars) == Approx(60.0));

        parser.setRawExpression("{0} + {1} * 2");
        func = parser.parse();

        arr = {1.5, 2.5};
        vars = {};

        REQUIRE(func(arr, vars) == Approx(6.5));

        parser.setRawExpression("x * {0}");
        func = parser.parse();

        arr = {5.0};
        vars = {{"x", 2}};

        REQUIRE(func(arr, vars) == Approx(10.0));

        parser.setRawExpression("level >= 10 && str > 5");
        func = parser.parse();

        arr = {};
        vars = {{"level", 12}, {"str", 6}};

        REQUIRE(func(arr, vars) == Approx(1.0));

        vars["str"] = 4;
        REQUIRE(func(arr, vars) == Approx(0.0));

        vars["level"] = 8;
        vars["str"] = 6;
        REQUIRE(func(arr, vars) == Approx(0.0));

        parser.setRawExpression("score / max_score * 100");
        func = parser.parse();

        arr = {};
        vars = {{"score", 80}, {"max_score", 100}};
        REQUIRE(func(arr, vars) == Approx(80.0));
    }
}

TEST_CASE("Parse: Invalid expressions", "[parse]") {
    cse498::ExpressionParser parser;

    SECTION("Missing variables") {
        parser.setRawExpression("x + 5");
        auto func = parser.parse();

        std::vector<double> arr = {};
        std::map<std::string, double> vars = {};

        REQUIRE_THROWS_AS(func(arr, vars), cse498::ExpressionException);

        vars["x"] = 2;
        REQUIRE(func(arr, vars) == Approx(7.0));

        parser.setRawExpression("a * b + c");
        func = parser.parse();

        vars = {{"a", 2}, {"b", 3}};
        REQUIRE_THROWS_AS(func(arr, vars), cse498::ExpressionException);

        vars["c"] = 4;
        REQUIRE(func(arr, vars) == Approx(10.0));
    }

    SECTION("Index out of bounds or missing") {
        parser.setRawExpression("{0} + 5");
        auto func = parser.parse();

        std::vector<double> arr = {};
        std::map<std::string, double> vars = {};

        REQUIRE_THROWS_AS(func(arr, vars), cse498::ExpressionException);

        arr.push_back(2);
        REQUIRE(func(arr, vars) == Approx(7.0));

        parser.setRawExpression("{1} * 3");
        func = parser.parse();

        arr = {1.5};
        REQUIRE_THROWS_AS(func(arr, vars), cse498::ExpressionException);

        arr.push_back(2.5);
        REQUIRE(func(arr, vars) == Approx(7.5));
    }

    SECTION("Division by zero") {
        parser.setRawExpression("10 / x");
        auto func = parser.parse();

        std::vector<double> arr = {};
        std::map<std::string, double> vars = {{"x", 0}};

        REQUIRE_THROWS_AS(func(arr, vars), cse498::ExpressionException);

        vars["x"] = 2;
        REQUIRE(func(arr, vars) == Approx(5.0));
    }

    // Generated by Gemini 3 Pro 2026-2-16, but under the supervision of author
    SECTION("Invalid operator usage") {
        parser.setRawExpression("3 + * 4");
        REQUIRE_THROWS_AS(parser.parse(), cse498::ExpressionException);

        parser.setRawExpression("x / / y");
        REQUIRE_THROWS_AS(parser.parse(), cse498::ExpressionException);

        parser.setRawExpression("a && || b");
        REQUIRE_THROWS_AS(parser.parse(), cse498::ExpressionException);

        parser.setRawExpression("* x + 1");
        REQUIRE_THROWS_AS(parser.parse(), cse498::ExpressionException);

        parser.setRawExpression("x + 1 -");
        REQUIRE_THROWS_AS(parser.parse(), cse498::ExpressionException);
    }

    // Generated by Gemini 3 Pro 2026-2-16, but under the supervision of author
    SECTION("Mismatched parentheses") {
        parser.setRawExpression("((x + 2)");
        REQUIRE_THROWS_AS(parser.parse(), cse498::ExpressionException);

        parser.setRawExpression("x + 2))");
        REQUIRE_THROWS_AS(parser.parse(), cse498::ExpressionException);

        parser.setRawExpression("((x + 2)) + (y * 3");
        REQUIRE_THROWS_AS(parser.parse(), cse498::ExpressionException);

        parser.setRawExpression("() + 5");
        REQUIRE_THROWS_AS(parser.parse(), cse498::ExpressionException);

        parser.setRawExpression(")(");
        REQUIRE_THROWS_AS(parser.parse(), cse498::ExpressionException);
    }
}