/// @file StepTrafficWorldTest.cpp
/// @brief Tests for StepTrafficWorld.

#include <catch2/catch_test_macros.hpp>
#include <fstream>
#include <optional>

#include "../source/Interfaces/IActionLog.hpp"
#include "../source/Worlds/StepTrafficWorld.hpp"

using namespace cse498;
using namespace cse498::steps;

// Agent that doesn't do anything and is used when the test only needs a
// placeholder in the world
class StillAgent : public StepAgentBase<TrafficData> {
 public:
  StillAgent(TrafficData d, size_t id, LogLevel loglevel = LogLevel::Normal,
             uint64_t tick = 0)
      : StepAgentBase<TrafficData>(d, id, loglevel, tick) {}
  [[nodiscard]] StepContainer GetTurn() override { return {}; }
  void SetGoal([[maybe_unused]] WorldPosition p) override {}
};

// Helps create deterministic tests, by allowing an agents next move to be set
// directly
class ScriptedTestAgent : public StepAgentBase<TrafficData> {
  std::optional<WorldPosition> next_{};

 public:
  ScriptedTestAgent(TrafficData d, size_t id,
                    LogLevel loglevel = LogLevel::Normal, uint64_t tick = 0)
      : StepAgentBase<TrafficData>(d, id, loglevel, tick) {}
  void SetNextMove(std::optional<WorldPosition> p) { next_ = p; }
  [[nodiscard]] StepContainer GetTurn() override {
    StepContainer c{};
    if (next_) c.add_step(MovementStep{*next_});
    return c;
  }
  void SetGoal([[maybe_unused]] WorldPosition p) override {}
};

// StillAgent is the world's default agent type. ScriptedTestAgent is used where
// a specific move sequence is needed.
using TestWorld = StepTrafficWorld<StillAgent>;

// Grids: '#'=grass '.'=road '|'=vert light '-'=horiz light 'S'=spawn
// 'D'=destination

// Lines 42-78 were generated by Claude
static const std::vector<std::string> kMinimal = {
    "#########",
    "#S..|..D#",  // S=col1  |=col4  D=col7  all row1
    "#########",
};
static const std::vector<std::string> kTiny = {
    "####",
    "#SD#",  // S=col1  D=col2  row1
    "####",
};
// kLine: plain road strip — used for collision and U-turn tests.
static const std::vector<std::string> kLine = {
    "#####",
    "#...#",
    "#####",
};
// kMulti: multiple spawners and destinations, used for the agent cap test.
static const std::vector<std::string> kMulti = {
    "###########", "#S..|..D.S#", "#.........#", "#D..-..S.D#", "###########",
};
static const std::vector<std::string> kVertApproach = {
    "#####",
    "#.|.#",  // | at col2 row1
    "#.|.#",  // | at col2 row2
    "#####",
};
static const std::vector<std::string> kHorizApproach = {
    "###",
    "#.#",  // road above '-'
    "#-#",  // - at col1 row2
    "#.#", "###",
};

// TrafficData with reasonable defaults for fields not being tested.
static TrafficData Make(WorldPosition pos,
                        std::optional<WorldPosition> dest = {},
                        Direction dir = Direction::East, bool active = true) {
  return TrafficData{dest, pos, dir, active, '>', ""};
}

// Write a grid to a temp file and return the path, for file-constructor tests.
static std::string TempGrid(const std::vector<std::string>& g,
                            const char* name = "_stw.txt") {
  std::ofstream f(name);
  for (auto& r : g) f << r << '\n';
  return name;
}

TEST_CASE("Construction", "[StepTrafficWorld][construction]") {
  SECTION("vector constructor — typical grid") {
    CHECK_NOTHROW(TestWorld{kMinimal});
  }
  SECTION("vector constructor — all grass") {
    TestWorld tw{std::vector<std::string>{"##", "##"}};
    CHECK(tw.GetDestinationColour(WorldPosition{0, 0}).empty());
  }
  SECTION("vector constructor — no spawner") {
    CHECK_NOTHROW(
        TestWorld{std::vector<std::string>{"#####", "#.D.#", "#####"}});
  }
  SECTION("vector constructor — no destination") {
    CHECK_NOTHROW(
        TestWorld{std::vector<std::string>{"#####", "#S..#", "#####"}});
  }
  SECTION("file constructor matches vector constructor colors") {
    // Both constructors should parse the grid identically, destination
    // color assignment is a good estimate for correct parsing.
    auto p = TempGrid(kMinimal);
    TestWorld fv{kMinimal}, ff{p};
    std::remove(p.c_str());
    CHECK(fv.GetDestinationColour(WorldPosition{7, 1}) ==
          ff.GetDestinationColour(WorldPosition{7, 1}));
  }
}

TEST_CASE("GetDestinationColour", "[StepTrafficWorld][accessors]") {
  TestWorld tw{kMinimal};
  SECTION("destination cell returns non-empty ANSI code") {
    CHECK_FALSE(tw.GetDestinationColour(WorldPosition{7, 1}).empty());
  }
  SECTION("road cell returns empty") {
    CHECK(tw.GetDestinationColour(WorldPosition{2, 1}).empty());
  }
  SECTION("grass cell returns empty") {
    CHECK(tw.GetDestinationColour(WorldPosition{0, 0}).empty());
  }
  SECTION("out-of-map position returns empty") {
    CHECK(tw.GetDestinationColour(WorldPosition{999, 999}).empty());
  }
  SECTION("stable across repeated calls") {
    WorldPosition d{7, 1};
    CHECK(tw.GetDestinationColour(d) == tw.GetDestinationColour(d));
  }
}

TEST_CASE("Grid query helpers", "[StepTrafficWorld][grid_queries]") {
  TestWorld tw{kMinimal};  // 9 wide × 3 tall

  SECTION("IsValid: interior true, out-of-bounds false") {
    CHECK(tw.IsValid(WorldPosition{4, 1}));
    CHECK_FALSE(tw.IsValid(WorldPosition{9, 1}));
  }
  SECTION("IsGrass: border '#' true, road '.' false, OOB false") {
    CHECK(tw.IsGrass(WorldPosition{0, 0}));
    CHECK_FALSE(tw.IsGrass(WorldPosition{2, 1}));
    CHECK_FALSE(tw.IsGrass(WorldPosition{999, 999}));
  }
  SECTION("HorizontalBlockedAt: true for '|', false for road, false for OOB") {
    CHECK(tw.HorizontalBlockedAt(WorldPosition{4, 1}));  // '|'
    CHECK_FALSE(tw.HorizontalBlockedAt(WorldPosition{2, 1}));
    CHECK_FALSE(tw.HorizontalBlockedAt(WorldPosition{999, 999}));
  }
  SECTION("VerticalBlockedAt: true for '-', false for '|', false for OOB") {
    TestWorld tw2{std::vector<std::string>{"###", "#-#", "###"}};
    CHECK(tw2.VerticalBlockedAt(WorldPosition{1, 1}));
    CHECK_FALSE(tw.VerticalBlockedAt(WorldPosition{4, 1}));
    CHECK_FALSE(tw.VerticalBlockedAt(WorldPosition{999, 999}));
  }
}

TEST_CASE("GetOppositeDirection", "[StepTrafficWorld][helpers]") {
  TestWorld tw{kMinimal};
  CHECK(tw.GetOppositeDirection(Direction::North) == Direction::South);
  CHECK(tw.GetOppositeDirection(Direction::South) == Direction::North);
  CHECK(tw.GetOppositeDirection(Direction::East) == Direction::West);
  CHECK(tw.GetOppositeDirection(Direction::West) == Direction::East);
  // Doing this twice should give back the original direction.
  for (Direction d :
       {Direction::North, Direction::South, Direction::East, Direction::West})
    CHECK(tw.GetOppositeDirection(tw.GetOppositeDirection(d)) == d);
}

TEST_CASE("DoAction", "[StepTrafficWorld][do_action]") {
  SECTION("inactive agent: position unchanged, still inactive") {
    TestWorld tw{kMinimal};
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{2, 1}, {}, Direction::East, false), 0,
        LogLevel::Normal, 0);
    a->SetNextMove(WorldPosition{3, 1});
    TrafficData r = tw.DoAction(a);
    CHECK(r.position == WorldPosition{2, 1});
    CHECK_FALSE(r.is_active);
  }
  SECTION("empty StepContainer: agent stays put") {
    TestWorld tw{kMinimal};
    auto a = std::make_shared<ScriptedTestAgent>(Make(WorldPosition{2, 1}), 0,
                                                 LogLevel::Normal, 0);
    CHECK(tw.DoAction(a).position == WorldPosition{2, 1});
  }
  SECTION("valid road move: position and direction updated") {
    TestWorld tw{kMinimal};
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{2, 1}, {}, Direction::East), 0, LogLevel::Normal, 0);
    a->SetNextMove(WorldPosition{3, 1});
    TrafficData r = tw.DoAction(a);
    CHECK(r.position == WorldPosition{3, 1});
    CHECK(r.direction == Direction::East);
  }
  SECTION("move into grass: silently ignored") {
    TestWorld tw{kMinimal};
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{2, 1}, {}, Direction::North), 0, LogLevel::Normal,
        0);
    a->SetNextMove(WorldPosition{2, 0});  // row 0 is all '#'
    CHECK(tw.DoAction(a).position == WorldPosition{2, 1});
  }
  SECTION("U-turn (backward move) rejected") {
    // Moving opposite to the current facing direction is not a valid action as
    // it would let agents reverse without turning, breaking road simulation.
    TestWorld tw{kLine};
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{2, 1}, {}, Direction::East), 0, LogLevel::Normal, 0);
    a->SetNextMove(WorldPosition{1, 1});  // west while facing east
    CHECK(tw.DoAction(a).position == WorldPosition{2, 1});
  }
  SECTION("diagonal move rejected") {
    TestWorld tw{kMinimal};
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{2, 1}, {}, Direction::East), 0, LogLevel::Normal, 0);
    a->SetNextMove(WorldPosition{3, 2});
    CHECK(tw.DoAction(a).position == WorldPosition{2, 1});
  }
  SECTION("vertical light blocks east move (initial ALLOW_VERTICAL phase)") {
    TestWorld tw{kMinimal};
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{3, 1}, {}, Direction::East), 0, LogLevel::Normal, 0);
    a->SetNextMove(WorldPosition{4, 1});  // into '|'
    CHECK(tw.DoAction(a).position == WorldPosition{3, 1});
  }
  SECTION("vertical light allows south move") {
    TestWorld tw{kVertApproach};
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{2, 1}, {}, Direction::South), 0, LogLevel::Normal,
        0);
    a->SetNextMove(WorldPosition{2, 2});
    TrafficData r = tw.DoAction(a);
    CHECK(r.position == WorldPosition{2, 2});
    CHECK(r.direction == Direction::South);
  }
  SECTION("horizontal light blocks south move") {
    TestWorld tw{kHorizApproach};
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{1, 1}, {}, Direction::South), 0, LogLevel::Normal,
        0);
    a->SetNextMove(WorldPosition{1, 2});  // into '-'
    CHECK(tw.DoAction(a).position == WorldPosition{1, 1});
  }
  SECTION("horizontal light allows east move") {
    TestWorld tw{std::vector<std::string>{"#####", "#.-.#", "#####"}};
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{1, 1}, {}, Direction::East), 0, LogLevel::Normal, 0);
    a->SetNextMove(WorldPosition{2, 1});
    CHECK(tw.DoAction(a).position == WorldPosition{2, 1});
  }
  SECTION("arrival at destination marks agent inactive") {
    // is_active == false is how the world signals a despawned agent.
    // RunAgents skips inactive agents on subsequent ticks.
    TestWorld tw{kTiny};
    WorldPosition dest{2, 1};
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{1, 1}, dest, Direction::East), 0, LogLevel::Normal,
        0);
    a->SetNextMove(dest);
    TrafficData r = tw.DoAction(a);
    CHECK(r.position == dest);
    CHECK_FALSE(r.is_active);
  }
  SECTION("symbol updated to match new direction after move") {
    TestWorld tw{
        std::vector<std::string>{"#####", "##.##", "#...#", "##.##", "#####"}};
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{2, 2}, {}, Direction::South), 0, LogLevel::Normal,
        0);
    a->SetNextMove(WorldPosition{2, 3});
    CHECK(tw.DoAction(a).symbol == 'v');
  }
}

TEST_CASE("CanCollideWithAgentAt", "[StepTrafficWorld][collision]") {
  SECTION("empty target cell: no collision") {
    TestWorld tw{kLine};
    CHECK_FALSE(tw.CanCollideWithAgentAt(Direction::East, WorldPosition{3, 1}));
  }
  SECTION("same-direction active agent ahead: collision") {
    // Two agents travelling the same direction should not occupy the same cell.
    // The rear agent must wait behind the front one.
    TestWorld tw{kLine};
    tw.AddAgent<StillAgent>(Make(WorldPosition{3, 1}, {}, Direction::East),
                            LogLevel::Normal, 0);
    CHECK(tw.CanCollideWithAgentAt(Direction::East, WorldPosition{3, 1}));
  }
  SECTION("inactive agent at target: no collision") {
    // Inactive agents are treated as absent for collision purposes.
    TestWorld tw{kLine};
    tw.AddAgent<StillAgent>(
        Make(WorldPosition{3, 1}, {}, Direction::East, false), LogLevel::Normal,
        0);
    CHECK_FALSE(tw.CanCollideWithAgentAt(Direction::East, WorldPosition{3, 1}));
  }
}

// traffic_light_period == 3.  Initial phase: ALLOW_VERTICAL, so '|' blocks east
// moves
TEST_CASE("UpdateWorld — traffic lights", "[StepTrafficWorld][update]") {
  SECTION("period-1 ticks: light unchanged, east move still blocked") {
    TestWorld tw{kMinimal};
    for (int i = 0; i < 2; ++i) tw.UpdateWorld();
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{3, 1}, {}, Direction::East), 0, LogLevel::Normal, 0);
    a->SetNextMove(WorldPosition{4, 1});
    CHECK(tw.DoAction(a).position == WorldPosition{3, 1});
  }
  SECTION("after 3 ticks: light flips, east move succeeds") {
    TestWorld tw{kMinimal};
    for (int i = 0; i < 3; ++i) tw.UpdateWorld();
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{3, 1}, {}, Direction::East), 0, LogLevel::Normal, 0);
    a->SetNextMove(WorldPosition{4, 1});
    CHECK(tw.DoAction(a).position == WorldPosition{4, 1});
  }
  SECTION("after 6 ticks: light back to original, east move blocked again") {
    TestWorld tw{kMinimal};
    for (int i = 0; i < 6; ++i) tw.UpdateWorld();
    auto a = std::make_shared<ScriptedTestAgent>(
        Make(WorldPosition{3, 1}, {}, Direction::East), 0, LogLevel::Normal, 0);
    a->SetNextMove(WorldPosition{4, 1});
    CHECK(tw.DoAction(a).position == WorldPosition{3, 1});
  }
}

TEST_CASE("UpdateWorld — spawners", "[StepTrafficWorld][update]") {
  SECTION("no-spawner world runs 60 ticks without crash") {
    TestWorld tw{std::vector<std::string>{"#######", "#..D..#", "#######"}};
    CHECK_NOTHROW([&] {
      for (int i = 0; i < 60; ++i) tw.UpdateWorld();
    }());
  }
  SECTION("max_spawned_agents cap (== 3) respected over many ticks") {
    TestWorld tw{kMulti};
    for (int i = 0; i < 400; ++i) tw.UpdateWorld();
    // We can only verify this doesn't crash since agent internals are private
    CHECK_NOTHROW((void)0);
  }
}

TEST_CASE("RunAgents", "[StepTrafficWorld][run_agents]") {
  SECTION("inactive agent position not changed by RunAgents") {
    TestWorld tw{kMinimal};
    auto& a = tw.AddAgent<ScriptedTestAgent>(
        Make(WorldPosition{2, 1}, {}, Direction::East, false), LogLevel::Normal,
        0);
    WorldPosition before = a.GetState().position;
    tw.RunAgents();
    CHECK(a.GetState().position == before);
  }
  SECTION("active agent with move step updates its position") {
    TestWorld tw{kMinimal};
    auto& a = tw.AddAgent<ScriptedTestAgent>(
        Make(WorldPosition{2, 1}, {}, Direction::East), LogLevel::Normal, 0);
    // AddAgent returns a StepAgentBase reference, need to cast back to
    // ScriptedTestAgent to call SetNextMove before RunAgents processes the
    // turn.
    static_cast<ScriptedTestAgent&>(a).SetNextMove(WorldPosition{3, 1});
    tw.RunAgents();
    CHECK(a.GetState().position == WorldPosition{3, 1});
  }
}

TEST_CASE("Edge cases", "[StepTrafficWorld][edge]") {
  SECTION("SetFrameDelay is chainable and does not crash") {
    TestWorld tw{kMinimal};
    CHECK_NOTHROW(tw.SetFrameDelay(std::chrono::milliseconds{0}));
  }
}
