
#include <emscripten.h>
#include <emscripten/val.h>

#include <catch2/catch_test_macros.hpp>

#include "tools/webui/WebButton.h"

using namespace cse498;

struct SetupMockDOMWebButton {
  SetupMockDOMWebButton() {
    // clang-format off
    EM_ASM({
      const { JSDOM } = jsdom;
      const dom = new JSDOM("<!DOCTYPE html> <html><head></head><body></body></html>");
      globalThis.window = dom.window;
      globalThis.document = dom.window.document;
      globalThis.AbortController = dom.window.AbortController;
      globalThis.AbortSignal = dom.window.AbortSignal;
      globalThis.FileReader = dom.window.FileReader;
    });
    // clang-format on
  }

  ~SetupMockDOMWebButton() {
    // clang-format off
    EM_ASM({
      if (globalThis.window && globalThis.window.close) {
        globalThis.window.close();
      }
      delete globalThis.document;
      delete globalThis.window;
      delete globalThis.AbortController;
      delete globalThis.AbortSignal;
      delete globalThis.FileReader;
    });
    // clang-format on
  }
};

TEST_CASE("WebButton basics") {
  SetupMockDOMWebButton mock;
  auto b = std::make_shared<cse498::WebButton>("Start",
                                               WebOptions{.id = "startBtn"});

  SECTION("Label set/get works") {
    REQUIRE(b->GetLabel() == "Start");
    b->SetLabel("Pause");
    REQUIRE(b->GetLabel() == "Pause");
  }

  SECTION("Visibility works") {
    REQUIRE(b->IsVisible());
    b->Hide();
    REQUIRE_FALSE(b->IsVisible());
    b->Show();
    REQUIRE(b->IsVisible());
  }

  SECTION("Enable/Disable works") {
    REQUIRE(b->IsEnabled());
    b->Disable();
    REQUIRE_FALSE(b->IsEnabled());
    b->Enable();
    REQUIRE(b->IsEnabled());
  }

  SECTION("Click runs callback only when enabled and visible") {
    int count = 0;
    b->SetOnClick([&count]() { ++count; });

    emscripten::val arg;

    b->Click(arg);
    REQUIRE(count == 1);

    b->Disable();
    b->Click(arg);
    REQUIRE(count == 1);

    b->Enable();
    b->Hide();
    b->Click(arg);
    REQUIRE(count == 1);

    b->Show();
    b->Click(arg);
    REQUIRE(count == 2);
  }
}

TEST_CASE("WebButton File Upload functionality") {
  SetupMockDOMWebButton mock;
  auto b = std::make_shared<cse498::WebButton>("Upload",
                                               WebOptions{.id = "uploadBtn"});

  SECTION("SetOnFileUpload extracts text and triggers callback") {
    std::string uploaded_content = "";

    // 1. Assign the C++ callback
    b->SetOnFileUpload([&uploaded_content](const std::string& file_text) {
      uploaded_content = file_text;
    });

    // 2. Mock the JavaScript event object generated by FileReader
    //    JS Equivalent: const event = { target: { result: "Simulated file
    //    content!" } };
    emscripten::val mock_target = emscripten::val::object();
    mock_target.set("result", std::string("Simulated file content!"));

    emscripten::val mock_event = emscripten::val::object();
    mock_event.set("target", mock_target);

    // 3. Trigger the internal callback exactly as the browser's FileReader
    // would
    b->OnFileReadCompleteInternal(mock_event);

    // 4. Verify the C++ string was populated successfully
    REQUIRE(uploaded_content == "Simulated file content!");
  }
}